name : "hello world workflow"

# controls when the actions will run , triggers the workflow on push some to main branch or production branch
on:
  push:
    branches:
      - main
      - prod 

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: "hello world step"
        run: echo "hello world"

      - name: "print date step"
        run: date