name : multi event pipeline / workflow
on: 
    push:
        branches:
            - main
            - test
    pull_request:
        branches:
            - main
            - test       

jobs:
    on-push-job:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "on push event"
              run: echo "this is on push event"
    on-pull-request-job:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "on pull request event"
              run: echo "this is on pull request event"           