name : multi event pipeline / workflow
on: 
    push:
        branches:
            - main
            - test
    schedule:
            - cron: '15 11 * * 2,5' # runs every day at midnight    
    pull_request:
        branches:
            - main
        types:
            - closed 
            - opened     
    workflow_dispatch:


jobs:
    on-push-job:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "on push event"
              run: echo "this is on push event"
    on-pull-request-job:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "on pull request event"
              run: echo "this is on pull request event"  
    on-pull-request-closed-job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "on pull request closed event"
              run: echo "this is on pull request closed event"             
    on-workflow-dispatch-job:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "on workflow dispatch event"
              run: echo "this is on workflow dispatch event"               
    on-schedule-job:
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        steps:
            - name: "on schedule event"
              run: echo "this is on schedule event"
